import {useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {Eye,EyeOff,ShieldCheck,ShoppingBag} from 'lucide-react'
import api from '../services/api';import {useAuth} from '../context/AuthContext'
export default function Login(){const [email,setEmail]=useState('demo@shopflow.com'),[password,setPassword]=useState('Demo@123'),[role,setRole]=useState('user'),[show,setShow]=useState(false),[err,setErr]=useState('');const {login}=useAuth();const nav=useNavigate()
 const submit=async e=>{e.preventDefault();setErr('');try{const r=await api.post('/auth/login',{email,password,role});login(r.data);nav('/app')}catch(x){setErr(x.response?.data?.detail||'Unable to login')}}
 return <div className="grid min-h-screen lg:grid-cols-2"><div className="hidden bg-slate-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="text-3xl font-black text-indigo-400">shop<span className="text-white">flow</span></div><div><ShoppingBag size={48} className="mb-6 text-indigo-400"/><h1 className="max-w-xl text-5xl font-bold leading-tight">Everything you need.<br/>One smart shopping flow.</h1><p className="mt-6 max-w-lg text-slate-400">A complete e-commerce experience with discovery, offers, wishlist, secure checkout and live order operations.</p></div><p className="text-sm text-slate-500">Day 10–13 Engineering Project</p></div>
 <div className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md"><div className="mb-8"><div className="text-2xl font-black text-indigo-600 lg:hidden">shopflow</div><h2 className="mt-5 text-3xl font-bold">Welcome back</h2><p className="mt-2 text-slate-500">Sign in to continue shopping.</p></div>{err&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{err}</div>}<label className="text-sm font-semibold">Email<input value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 mb-4 w-full rounded-xl border p-3 outline-none focus:border-indigo-500"/></label><label className="text-sm font-semibold">Password<div className="relative"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-xl border p-3 pr-11 outline-none focus:border-indigo-500"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-4">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={()=>setRole('user')} className={`rounded-xl border p-3 text-sm ${role==='user'?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200'}`}>Customer</button><button type="button" onClick={()=>setRole('admin')} className={`rounded-xl border p-3 text-sm ${role==='admin'?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200'}`}><ShieldCheck className="mr-1 inline" size={16}/>Admin</button></div><button className="mt-5 w-full rounded-xl bg-indigo-600 py-3.5 font-semibold text-white hover:bg-indigo-700">Sign In</button><p className="mt-5 text-center text-sm text-slate-500">New to ShopFlow? <Link to="/register" className="font-semibold text-indigo-600">Create account</Link></p><p className="mt-6 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Demo customer: demo@shopflow.com / Demo@123<br/>Demo admin: admin@shopflow.com / Admin@123</p></form></div></div>
}

